export IWESOL_CPP_LIB=/home/jonas/temp/terrainBlockMesher/iwesol/iwesolCppLibs/lib
export IWESOL_BLIB=/home/jonas/temp/terrainBlockMesher/iwesol/iwesolCppLibs/blib
export IWESOL_FOAM_TOOLS=/home/jonas/temp/terrainBlockMesher/iwesol/iwesolFoamTools
export IWESOL_DOC=/home/jonas/temp/terrainBlockMesher/iwesol/doc
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$IWESOL_CPP_LIB
